name: Create Release

on:
  push:
    branches:
    - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Run Unit Tests
      run: ./scripts/unit.sh
    - name: Run Integration Tests
      run: ./scripts/integration.sh
    - name: Tag
      id: tag
      run: |
        TAG="$(./.github/util/tag.sh)"
        echo "::set-output name=tag::$TAG"
    - name: Package
      env:
        TAG: ${{ steps.tag.outputs.tag }}
      run: PACKAGE_DIR=artifact ./scripts/package.sh --version "${TAG}" --archive
    - name: Create Release Notes
      id: create-release-notes
      run: |
        go install github.com/cloudfoundry/packit/cargo/jam
        RELEASE_BODY=$($HOME/go/bin/jam summarize --buildpack "${PWD}/artifact.tgz" --format markdown)
        # Coz of this messed up issue
        # https://github.community/t5/GitHub-Actions/set-output-Truncates-Multiline-Strings/m-p/38372#M3322
        RELEASE_BODY="${RELEASE_BODY//'%'/'%25'}"
        RELEASE_BODY="${RELEASE_BODY//$'\n'/'%0A'}"
        RELEASE_BODY="${RELEASE_BODY//$'\r'/'%0D'}"
        echo "::set-output name=release_body::$RELEASE_BODY"
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: ${{ steps.tag.outputs.tag }}
        body: ${{ steps.create-release-notes.outputs.release_body }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: artifact.tgz
        asset_name: ${{ github.event.repository.name }}-${{ steps.tag.outputs.tag }}.tgz
        asset_content_type: application/gzip

